# Configuration preset for map2lp.py
# Results in a map brightly colored for showing in the asprilo visualizer, albeit with nonsensical meaning.

# Dictionary to translate symbols found in original map.
# Format: <character>: <List of object predicates to generate>
# Example: "T": ["node", "tree"] translates every "T" as two separate init-statements one for a node and one for a tree.
"term_dict":
  ".":
    - "node"
  "G":
    - "node"
  "T":
    - "node"
    - "tree"
  "W":
    - "node"
    - "water"
  "S":
    - "node"
    - "swamp"

# List of ignored symbols in original file when converting:
"ignore_list":
    -"@"
    -"O"

# Template for logic statements in output file:
"statement_template": "init(object({},{}),value(at,({},{}))).\n"
