# Configuration preset for map-to-asprilo and scen-to-asprilo
# Results in a "binary" map with a node on exactly every tile without movement restrictions
# and no other literals,
# and scenarios comprising <parameter>(<value>,<index>) - statements.

# Dictionary to translate symbols found in original map.
# Format: <character>: <List of object predicates to generate>
# Example: "T": ["node", "tree"] translates every "T" as two separate init-statements one for a node and one for a tree.
"term_dict":
  ".":
    - "node"
  "G":
    - "node"

# List of ignored symbols in original file when converting:
"ignore_list":
  - "@"
  - "O"
  - "W"
  - "T"
  - "S"

# Template for logic statements in output file:
"statement_template": "init(object({},{}),value(at,({},{}))).\n"

# Dictionary to translate parameters in .scen-files to statements.
"param_dict":

  "bucket": ~

  "map": "map(\"{}\",{}).\n"

  "map_width": "map_width({},{}).\n"

  "map_height": "map_height({},{}).\n"

  "start_x": "start_x({},{}).\n"

  "start_y": "start_y({},{}).\n"

  "goal_x": "goal_x({},{}).\n"

  "goal_y": "goal_y({},{}).\n"

  "optimal_length": ~