# Configuration preset for map2lp.py
# Results in a "binary" map with a node on exactly every tile without movement restrictions
# and no other literals.

# Term Dictionary:
"term_dict":
  ".":
    - "node"
  "G":
    - "node"

# Ignore list:
"ignore_list":
  - "@"
  - "O"
  - "W"
  - "T"
  - "S"

# Statement template:
"statement_template": "init(object({},{}),value(at,({},{}))).\n"